### ISSUE TITLE
How can I test on my own sequential datasets?

### ISSUE THREAD

**Issue by dlwns97** [haofeixu/gmflow#30]
Hi, I'm really thank you for expressing gratitude for the release of your project.

I have done training GMFlow on Kitti dataset and not I want to evaluate it on my own sequential dataset.

But I am currently facing some difficulties in carrying out the task.

How can I get result (epe, visualizing the flow) on my own dataset.

Thanks again for your work.

**Comment by dlwns97** [comment]
Maybe I think I can use inference_dir, do you have any advice?

Thank you.

**Comment by dlwns97** [comment]
Oh, sorry that I missed demo.sh, I just view evaluate.py and evaluate.sh files.

Thank you for immediate answer!!

Additionally, I wonder what the colors on the flow_visualize png files are meaning.
I fixed some blockage on camera so two images have common black background that are not moving on the side,
But in flow png file it also shows some color on it not white color. (I want to catch the blockage on camera that does not move)
Can you give me the information about it?

**Comment by haofeixu** [comment]
Hi, here is the color map for flow visualization, where the color denotes the flow direction and intensity denotes the flow magnitude.

<img width="82" alt="image" src="https://github.com/haofeixu/gmflow/assets/19343475/d36d59c7-474d-4c0e-b5a3-f9060c8d56cd">

It's possible that the predicted flows are not exactly zero for fully static pixels (the training data contains very few cases), and thus the visualization might produce color instead of white. One workaround is to try to threshold the predicted flow, for example, by setting flow smaller than a threshold as 0.

**Comment by dlwns97** [comment]
It would be the great way to solve my problem.

Again, really really thank you for reply.

I will keep follow your works!! I hope you make great things again!

**Comment by haofeixu** [comment]
Thanks for your kind words and wish you all the best!
